apiVersion: v1
kind: Service

metadata:
  name: signalrank-api
  namespace: signalrank

spec:
  type: ClusterIP

  selector:
    app: signalrank-api

  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP