apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/hpa.yaml

configMapGenerator:
  - name: signalrank-smoke-data
    namespace: signalrank
    files:
      - smoke.txt=smoke-data/smoke.txt

  - name: signalrank-ci-config
    namespace: signalrank
    files:
      - kubernetes-ci.yaml=config/kubernetes-ci.yaml

generatorOptions:
  disableNameSuffixHash: true